# Generated by Django 5.0 on 2024-01-08 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(default="Name", max_length=200)),
                ("last_name", models.CharField(default="Name", max_length=200)),
                (
                    "contact_no",
                    models.ImageField(default="Profile", upload_to="profile"),
                ),
                ("Dob", models.CharField(default="Dob", max_length=200)),
                ("Contact", models.CharField(default="Contact", max_length=200)),
                ("Address", models.CharField(default="Address", max_length=200)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
