# Generated by Django 5.0 on 2024-01-08 21:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="about",
            name="contact_no",
        ),
    ]
